// app/LayoutRouter.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/NavbarComponent.jsx";
import ContentComponent from "@/components/ContentComponent.jsx";
import FooterComponent from "@/components/FooterComponent.jsx";
import { cookies } from "next/headers";
import ReduxProvider from "../provider/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "FoodExpress - Order Management System",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const token = cookieStore.get("session_token");

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReduxProvider>
          <NavbarComponent isAuthenticated={!!token} />
          <ContentComponent>
              {children}
          </ContentComponent>
          <FooterComponent />
        </ReduxProvider>
      </body>
    </html>
  );
} 
